version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: database-container
    environment:
      - MYSQL_ROOT_PASSWORD=badhansaha
      - MYSQL_DATABASE=expense_db
      - MYSQL_USER=webserver
      - MYSQL_PASSWORD=bjit@23
    volumes:
      - /home/badhan/projectwork/mysql_data:/var/lib/mysql
    networks:
      - project-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: badhan30078/docker-project:1.0
    container_name: webserver-container
    ports:
      - 80:8080
    volumes:
      - /home/badhan/projectwork/nginx_data:/var/www/html
    networks:
      - project-network
    depends_on:
      - mysql

networks:
  project-network:

volumes:
  mysql_data:
  nginx_data:

